// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FullStackDevExercise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace FullStackDevExercise
{
    public partial class MedStudyContext : DbContext
    {
        public MedStudyContext()
        {
        }

        public MedStudyContext(DbContextOptions<MedStudyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
    }
}
