// <auto-generated />
using System;
using FullStackDevExercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStackDevExercise.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210225201632_SeedInit")]
    partial class SeedInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Owner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("id");

                    b.ToTable("owners");

                    b.HasData(
                        new
                        {
                            id = 1,
                            firstName = "Rony",
                            lastName = "Jose"
                        },
                        new
                        {
                            id = 2,
                            firstName = "Ann",
                            lastName = "Jose"
                        });
                });

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Pet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("owner_id");

                    b.ToTable("pets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 1,
                            name = "Dude",
                            type = "Huskey Dog"
                        });
                });

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Pet", b =>
                {
                    b.HasOne("FullStackDevExercise.Data.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("owner_id");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
