// <auto-generated />
using System;
using FullStackDevExercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStackDevExercise.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("appointment_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("pet_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("slot_from")
                        .HasColumnType("INTEGER");

                    b.Property<int>("slot_to")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("pet_id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Owner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("first_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("owners");

                    b.HasData(
                        new
                        {
                            id = 1,
                            first_name = "Peter",
                            last_name = "Pan"
                        });
                });

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Pet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("owner_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("owner_id");

                    b.ToTable("pets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 1,
                            name = "Duke",
                            owner_id = 1,
                            type = "dog"
                        });
                });

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Appointment", b =>
                {
                    b.HasOne("FullStackDevExercise.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("pet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("FullStackDevExercise.Data.Entities.Pet", b =>
                {
                    b.HasOne("FullStackDevExercise.Data.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
